# Generated by Django 3.2.9 on 2021-11-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED_LIKE_NEW', 'Used - Like New'), ('USED_GOOD', 'Useed - Good'), ('USED_FAIR', 'Used - Fair')], default='NEW', max_length=13),
        ),
    ]
