# Generated by Django 3.2.9 on 2021-11-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0003_auto_20211130_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
