# Generated by Django 3.2.9 on 2021-11-30 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
