# Generated by Django 3.2.9 on 2021-11-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0005_listing_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='uuid',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(upload_to='atlas_mart/listing_images'),
        ),
    ]
